### ISSUE TITLE
dlib python failes to compile with numpy error.

### ISSUE THREAD

**Issue by IWriteThings** [davisking/dlib#1006]
## Expected Behavior
dlib python should compile.

## Current Behavior
dlib python failes at 97% complete.

```
from /home/aaron/Development/tmp/dlib/tools/python/src/numpy_returns.cpp:1:
/home/aaron/Development/tmp/dlib/tools/python/src/numpy_returns.cpp: In function ‘void bind_numpy_returns()’:
/usr/lib/python3.6/site-packages/numpy/core/include/numpy/__multiarray_api.h:1532:35: error: return-statement with a value, in function returning 'void' [-fpermissive]
 #define NUMPY_IMPORT_ARRAY_RETVAL NULL
                                   ^
/usr/lib/python3.6/site-packages/numpy/core/include/numpy/__multiarray_api.h:1537:151: note: in expansion of macro ‘NUMPY_IMPORT_ARRAY_RETVAL’
 #define import_array() {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return NUMPY_IMPORT_ARRAY_RETVAL; } }
                                                                                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/aaron/Development/tmp/dlib/tools/python/src/numpy_returns.cpp:131:5: note: in expansion of macro ‘import_array’
     import_array();
     ^
make[2]: *** [CMakeFiles/dlib_.dir/build.make:519: CMakeFiles/dlib_.dir/src/numpy_returns.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/dlib_.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
error: cmake build failed!

```

## Steps to Reproduce
`python3 setup.py install --yes USE_AVX_INSTRUCTIONS;`

* **Version**: latest
* **Where did you get dlib**: github
* **Platform**: 
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	17.1pre3
Codename:	Hakoila
* **Compiler**:gcc-6

I performed a pip install numpy. Still fails.

**Comment by davisking** [comment]
Thanks for the bug report.  I just updated the code, try it and let me know.

**Comment by IWriteThings** [comment]
Perfect! All fixed!

**Comment by davisking** [comment]
Actually, pull it again and try it now.  There was a problem with the first fix.

**Comment by IWriteThings** [comment]
Recompiled.

It has now changed an error I am getting for another project. Still have an error, but the error itself is new.

Thanks.

**Comment by davisking** [comment]
Ok, so not working or working? :)

**Comment by IWriteThings** [comment]
I believe dlib is fin e but I am getting errors in another project.

https://github.com/ageitgey/face_recognition/issues/257#issuecomment-350519631

The issue is found at the above link. Could you take a peak and just verify this has nothing to do with dlib? Everything here compiles now.

Thanks a bunch!

**Comment by IWriteThings** [comment]
I will post the error here just incase.

```
Traceback (most recent call last):
  File "example.py", line 12, in <module>
    compare_faces(unknown_persons,known_list)
  File "/home/aaron/Development/bulk-image-facial-recognition/ml_face.py", line 36, in compare_faces
    recognize_faces(image)
  File "/home/aaron/Development/bulk-image-facial-recognition/ml_face.py", line 19, in recognize_faces
    face_locations = face_recognition.face_locations(image, model="cnn")
  File "/usr/lib/python3.6/site-packages/face_recognition/api.py", line 111, in face_locations
    return [_trim_css_to_bounds(_rect_to_css(face.rect), img.shape) for face in _raw_face_locations(img, number_of_times_to_upsample, "cnn")]
  File "/usr/lib/python3.6/site-packages/face_recognition/api.py", line 95, in _raw_face_locations
    return cnn_face_detector(img, number_of_times_to_upsample)
RuntimeError: Error while calling cudaMalloc(&data, new_size*sizeof(float)) in file /home/aaron/Development/tmp/dlib/dlib/dnn/gpu_data.cpp:195. code: 2, reason: out of memory
```

**Comment by davisking** [comment]
Na, that's just your computer not having enough RAM :)
